### ISSUE TITLE
Consider making the tests follow JUnit 5 idioms more closely

### ISSUE THREAD

**Issue by jbduncan** [google/mug#1]
@fluentfuture Currently, the tests use a combination of JUnit 4 and JUnit 5 annotations which don't seem to follow the advice laid out in the JUnit 5 User Guide. I fear that this may make the tests, as they stand, prone to bugs and difficult to maintain over time.

The following sections from the JUnit 5 User Guide look like good starting points for resolving this issue:
- http://junit.org/junit5/docs/current/user-guide/#running-tests-junit-platform-runner
- http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4

**Comment by fluentfuture** [comment]
Only reason JUnit 5 was included was to have `assertThrows()`.

Inside Google, we use JU4 with backported assertThrows().

I guess we could migrate to JU5. My only concern would be the deviation from Google's internal tests, making it harder to move code one way or another.

**Comment by jbduncan** [comment]
> Only reason JUnit 5 was included was to have assertThrows().
>
> Inside Google, we use JU4 with backported assertThrows().

Ah okay, I see. That makes sense to me.

> I guess we could migrate to JU5. My only concern would be the deviation from Google's internal tests, making it harder to move code one way or another.

Okay, I think I understand your concerns here.

How about we change the `pom.xml`s so that rather than importing `junit-platform-runner`, they import `junit:junit:4.x` instead?

That way, it's more explicit (in my mind at least) that we're still using JUnit 4 as the underlying "test engine", but that we're merely importing `org.junit.jupiter:junit-jupiter-api:5.0.0-M3` to have access to `assertThrows()` (in a similar way to how we currently use Truth to have access to more assertions).

**Comment by fluentfuture** [comment]
Sounds good! Care to send a PR? :)

**Comment by jbduncan** [comment]
Happily! :)

Here's the [PR](https://github.com/google/mug/pull/2), FYI.

**Comment by fluentfuture** [comment]
Thanks!
