### ISSUE TITLE
Problem with Java 8 compilation

### ISSUE THREAD

**Issue by bihu1** [google/mug#12]
ReadMe says : "A small Java 8 utilities library (javadoc), with 0 deps.", unfortunately compilation with Java 8 gives this error: 
"java.lang.UnsupportedClassVersionError: com/google/mu/util/stream/BiStream has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0"
In Java 9 or later it works well. Can you get Java 8 support?

**Comment by fluentfuture** [comment]
PR merged.
