### ISSUE TITLE
The type of toImmutableListMultimap(Function<? super E,? extends Object>, Function<? super E,? extends Object>) from the type ImmutableListMultimap is Collector<E,?,ImmutableListMultimap<Object,Object>>, this is incompatible with the descriptor's return type: Collector<E,?,Object>

### ISSUE THREAD

**Issue by FanJups** [google/mug#18]
I got a red cross while working with eclipse 2019 09

Where ? **_module mug, src/test/java,  com.google.mu.util.stream.BiCollectorsTest.java_**

```
@Test public void testFlatMapping_toBiStream() {
    BiStream<String, Integer> salaries = BiStream.of("Joe", 1, "Tom", 2);
    ImmutableListMultimap<String, Integer> result = salaries.collect(
        BiCollectors.flatMapping(
            (k, c) -> BiStream.from(nCopies(c, k), identity(), unused -> c),
            ImmutableListMultimap::toImmutableListMultimap));
    assertThat(result)
        .containsExactly("Joe", 1, "Tom", 2, "Tom", 2)
        .inOrder();
  }
```

Message : **_The type of toImmutableListMultimap(Function<? super E,? extends Object>, Function<? super E,? extends Object>) from the type ImmutableListMultimap is Collector<E,?,ImmutableListMultimap<Object,Object>>, this is incompatible with the descriptor's return type: Collector<E,?,Object>_**

**But the build is successful.**

Do you get the same error ?

**Comment by fluentfuture** [comment]
I get it too. It seems the Eclipse compiler isn't consistent with Open JDK.

Feel free to tweak it to make it compile for both javac and Eclipse.

**Comment by fluentfuture** [comment]
I believe I should have fixed Eclipse compilation. Please give it a try.
