### ISSUE TITLE
javadoc link not found

### ISSUE THREAD

**Issue by phraktle** [google/mug#32]
The javadoc linked in the readme is currently 404: https://google.github.io/mug/apidocs/index.html

**Comment by ttsuchif** [comment]
+1... workaround is using the [wayback machine](https://web.archive.org/web/20220627175915/https://google.github.io/mug/apidocs/index.html), but I'd like the JavaDoc fixed too. Thanks!

**Comment by fluentfuture** [comment]
Fxed.
