### ISSUE TITLE
What is the canonical way to parallelStream over a map?

### ISSUE THREAD

**Issue by nakulj** [google/mug#72]
Since the 3-arg version of [from](https://google.github.io/mug/apidocs/com/google/mu/util/stream/BiStream.html#from(java.util.stream.Stream,java.util.function.Function,java.util.function.Function)) is deprecated, we are left with doing this:

```java
Map<K,V> foo;
biStream(Map.Entry::getKey, foo.entrySet().parallelStream())
  .mapValues(Map.Entry::getValue)
...
```

which doesn't have the immediate translation of code to intent that one might like.

Some options:
1. Bring back `BiStream.from(stream, toKey, toValue)` (not sure why this was ever deprecated in the first place)
2. Create parallel versions of `from`; eg. `BiStream.parallelFrom(Map)`
3. Add a parallelize flag to the existing methods

**Comment by fluentfuture** [comment]
There is the single-arg `biStream(stream)` you could use.

Although do note that `.collect(BiCollector)` is sequential regardless of the input Stream. I guess you could `mapToObj()` out to keep it parallel.
